export const statements = [
    {statement: "The number of articles", number: 3887},
    {statement: "The number of links", number: 5263},
    {statement: "The number of organizations without a website", number: 1179},
    {statement: "The number of organizations without a description", number: 1639},
    {statement: "The number of organizations without a location", number: 3455},
    {statement: "The number of articles without a summary", number: 443},
    {statement: "The number of articles without a problem definition", number: 3167},
    {statement: "The number of articles without a solution", number: 3149},
    {statement: "The number of articles without an outcome", number: 3292},
    {statement: "The number of articles without additional info", number: 3412},
    {statement: "The number of articles without an url", number: 1978},
    {statement: "The number of framework elements without a description", number: 109},
    {statement: "The number of frameworks without a description", number: 11},
]